import { Entity, Column, PrimaryGeneratedColumn, OneToOne } from "typeorm";
import { User } from './User';
import * as crypto from 'crypto';

@Entity('pass_reset_tokens')
export class PassResetToken {

  /** Autogenerated id as an integer. */
  @PrimaryGeneratedColumn()
  id: number

  /** 16 character long hex code to be attatched to password reset url */
  @Column()
  code: string

  /** Expiration date of this token as a UNIX timestamp. */
  @Column({type:'bigint'})
  expiration: number;

  /** The User this token is associated with. */
  @OneToOne(type => User)
  user: User;
}
