import { Entity, Column, PrimaryGeneratedColumn, ManyToOne, ManyToMany, JoinTable } from "typeorm";
import { SoftSkill } from "./SoftSkill";
import { User } from "./User";

/** Represents a request by a client for a new Program to be created */
@Entity('program_requests')
export class ProgramRequest {
  /** Autogenerated id as a UUID string. */
  @PrimaryGeneratedColumn("uuid")
  id: string;

  /** Text describing the requested Program. Nullable. */
  @Column({nullable: true})
  text: string;

  /** Client that entered this request. */
  @ManyToOne(type => User, user => user.programRequests)
  client: User;

  /** Soft Skills to be included in the requested Program. */
  @ManyToMany(type => SoftSkill, softSkills => softSkills.programRequests)
  @JoinTable()
  softSkills: SoftSkill[];
}
