import { Entity, Column, PrimaryGeneratedColumn, ManyToOne, ManyToMany, JoinTable, getRepository } from "typeorm";
import { SoftSkill, SoftSkillType } from "./SoftSkill";
import { User } from "./User";

/** Represents a request by a client for a new Program to be created */
@Entity('program_requests')
export class ProgramRequest {
  /** Autogenerated id as a UUID string. */
  @PrimaryGeneratedColumn("uuid")
  id: string;

  /** Text describing the requested Program. Nullable. */
  @Column({nullable: true})
  text: string;

  /** Client that entered this request. */
  @ManyToOne(type => User, user => user.programRequests)
  client: User;

  /** Soft Skills to be included in the requested Program. */
  @ManyToMany(type => SoftSkill, softSkills => softSkills.programRequests)
  @JoinTable()
  softSkills: SoftSkill[];

  /** Saves a new ProgramRequest to the database. */
  public static async saveNewAsync(requestOptions: NewProgramRequestOptions): Promise<ProgramRequest> {
    let requestRepo = getRepository(ProgramRequest);
    let softSkills: SoftSkill[] = [];
    if (requestOptions.softSkills) {
      await Promise.all(requestOptions.softSkills.map(async (skillType) => {
        softSkills.push(await SoftSkill.findByNameAsync(skillType));
        return;
      }));
    }
    let newRequest = new ProgramRequest();
      newRequest.client = requestOptions.client;
      newRequest.text = requestOptions.text;
      newRequest.softSkills = softSkills;
    return requestRepo.save(newRequest);
  }
}

/** All options required to create a new ProgramRequest. */
export interface NewProgramRequestOptions {
  /** Client that entered this request. */
  client: User;
  /** Text describing the requested Program. */
  text: string;
  /** Soft Skills to be included in the requested Program. Optional. */
  softSkills?: SoftSkillType[];
}
