import { Entity, Column, PrimaryGeneratedColumn, ManyToOne } from "typeorm";
import { User } from "./User";
import { Video } from "./Video";
import { Program } from "./Program";

/** Represents a subject's response to a Video in a Program, to be assesed by an admin. */
@Entity('responses')
export class Response {
  /** Autogenerated id as a UUID string. */
  @PrimaryGeneratedColumn("uuid")
  id: string;

  /** URL of the subject's audio response to the video. */
  @Column({nullable: true})
  gs_path: string;

  /** Speech-to-text parse of the audio response. Nullable. */
  @Column({nullable: true})
  text_version: string;

  /** Score assigned by an admin during assessment of the Response. */
  @Column({nullable: true})
  score: number;

  /** Whether this Response has been reviewed by an admin. */
  @Column()
  reviewed: boolean;

  /** The subject that this Response belongs to. */
  @ManyToOne(type => User, user => user.responses)
  subject: User;

  /** The Video that this was a Response to. */
  @ManyToOne(type => Video, video => video.responses)
  video: Video;

  /** The Program that this Response belongs to. */
  @ManyToOne(type => Program, program => program.responses)
  program: Program;

  public getGoogleStorageUri(): string {
    if (!this.gs_path) {
      return null;
    }
    return `gs://${this.gs_path}`;
  }

  public getResourceUrl(): string {
    if (!this.gs_path) {
      return null;
    }
    return `https://storage.cloud.google.com/${this.gs_path}`;
  }
}
