import { Entity, Column, PrimaryGeneratedColumn, OneToMany } from "typeorm";
import { User } from "./User";

/** User roles defining permissions. */
@Entity('roles')
export class Role {
  /** Autogenerated id as an integer. */
  @PrimaryGeneratedColumn()
  id: number;

  /** Name of the Role. */
  @Column()
  name: RoleType;

  /** All users with this Role */
  @OneToMany(type => User, users => users.role)
  users: User[];
}

/** Enumerated list of all role names. */
export enum RoleType {
  Admin = "ADMIN",
  Client = "CLIENT",
  Subject = "SUBJECT"
}
