import { Entity, Column, PrimaryGeneratedColumn, ManyToMany, getRepository } from "typeorm";
import { ProgramRequest } from "./ProgramRequest";

/** Represents a soft skill that a client can request. */
@Entity('soft_skills')
export class SoftSkill {
  /** Autogenerated id as an integer. */
  @PrimaryGeneratedColumn()
  id: number;

  /** Name of the soft skill. */
  @Column()
  name: string;

  /** All requests requesting this soft skill. */
  @ManyToMany(type => ProgramRequest, programRequests => programRequests.softSkills)
  programRequests: ProgramRequest[];

  /** Saves all soft skills in the SoftSkillNames enum to the database. */
  public static async syncSoftSkillsToDbAsync() {
    let skillRepo = getRepository(SoftSkill);
    let skillList = Object.values(SoftSkillType);
    await Promise.all(skillList.map(async (skillName) => {
      let skillFinder = await skillRepo.findOne({name: skillName});
      if (!skillFinder) {
        let newSoftSkill = new SoftSkill();
        newSoftSkill.name = skillName;
        await skillRepo.save(newSoftSkill);
      }
      return;
    }));
  }

  /** Retrieves a soft skill from the database by its SoftSkillType */
  public static async findByNameAsync(skillName: SoftSkillType): Promise<SoftSkill> {
    return getRepository(SoftSkill).findOne({name: skillName});
  }
}

/** Enumerated list of all soft skill names. */
export enum SoftSkillType {
  Test1 = "test1",
  Test2 = "test2",
  Test3 = "test3",
  Test4 = "test4",
  Test5 = "test5",
}
