import { Entity, Column, PrimaryGeneratedColumn, ManyToMany } from "typeorm";
import { ProgramRequest } from "./ProgramRequest";
import { Video } from './Video';

/** Represents a soft skill that a client can request. */
@Entity('soft_skills')
export class SoftSkill {
  /** Autogenerated id as an integer. */
  @PrimaryGeneratedColumn()
  id: number;

  /** Name of the soft skill. */
  @Column()
  name: string;

  /** All requests requesting this soft skill. */
  @ManyToMany(type => ProgramRequest, programRequests => programRequests.softSkills)
  programRequests: ProgramRequest[];

  /** All videos this soft skill is related too */
  @ManyToMany(type => Video, videos => videos.softSkills)
  videos: Video[];
}

/** Enumerated list of all soft skill names. */
export enum SoftSkillType {
  StrongWorkEthic = "Strong Work Ethic",
  PositiveAttitude = "Positive Attitude",
  GoodCommunicationSkills = "Good Communication Skills",
  TimeManagementAbilities = "Time Management Abilities",
  ProblemSolvingSkills = "Problem-Solving Skills",
  ActingAsATeamPlayer = "Acting as a Team Player",
  SelfConfidence = "Self-Confidence",
  AbilityToAcceptCriticism = "Ability to Accept and Learn From Criticism",
  FlexibilityAdaptability = "Flexibility/Adaptability",
  WorkingWellUnderPressure = "Working Well Under Pressure",
}
