import { Entity, Column, PrimaryGeneratedColumn, ManyToMany } from "typeorm";
import { Video } from "./Video";

/** Descriptive tag for a video. */
@Entity('tags')
export class Tag {
  /** Autogenerated id as an integer. */
  @PrimaryGeneratedColumn()
  id: number;

  /** Name of the tag. */
  @Column()
  name: string;

  /** All videos with this tag. */
  @ManyToMany(type => Video, videos => videos.tags)
  videos: Video[];
}

/** Enumerated list of all tag names. */
export enum TagType {
  Customer = "Customer",
  Angry = "Angry",
  Criticism = "Criticism",
  Pressure = "Pressure",
  Self = "Self",
}
