import { Entity, Column, PrimaryGeneratedColumn, ManyToMany, getRepository } from "typeorm";
import { Video } from "./Video";

/** Descriptive tag for a video. */
@Entity('tags')
export class Tag {
  /** Autogenerated id as an integer. */
  @PrimaryGeneratedColumn()
  id: number;

  /** Name of the tag. */
  @Column()
  name: string;

  /** All videos with this tag. */
  @ManyToMany(type => Video, videos => videos.tags)
  videos: Video[];

  /** Saves all tags in the TagNames enum to the database. */
  public static async syncTagsToDbAsync() {
    let tagRepo = getRepository(Tag);
    let tagList = Object.values(TagName);
    await Promise.all(tagList.map(async (tagName) => {
      let tagFinder = await tagRepo.findOne({name: tagName});
      if (!tagFinder) {
        let newTag = new Tag();
        newTag.name = tagName;
        await tagRepo.save(newTag);
      }
      return;
    }));
  }

  /** Retrieves a Tag from the database by its TagName */
  public static async findByNameAsync(tagName: TagName): Promise<Tag> {
    return getRepository(Tag).findOne({name: tagName});
  }
}

/** Enumerated list of all tag names. */
export enum TagName {
  Test1 = "test1",
  Test2 = "test2",
  Test3 = "test3",
  Test4 = "test4",
  Test5 = "test5",
}
