import { Entity, Column, PrimaryGeneratedColumn, OneToOne } from "typeorm";
import { User } from "./User";
import * as crypto from 'crypto';

@Entity('validation_tokens')
/** Token generated for email validation of Users. */
export class ValidationToken {
  /** Autogenerated id as an integer. */
  @PrimaryGeneratedColumn()
  id: number;

  /** Validation code generated by this token. */
  @Column()
  code: string;

  /** Expiration date of this token as a UNIX timestamp. */
  @Column({type:'bigint'})
  expiration: number;

  /** The User this token is associated with. */
  @OneToOne(type => User)
  user: User;
}
