import { Entity, Column, PrimaryGeneratedColumn, OneToMany, ManyToMany, JoinTable, getRepository } from "typeorm";
import { Program } from './Program';
import { Tag, TagName } from "./Tag";
import { Response } from "./Response";

/** A video object. */
@Entity('videos')
export class Video {
  /** Autogenerated id as a UUID string. */
  @PrimaryGeneratedColumn("uuid")
  id: string;

  /** The URL where this video is stored. Nullable. */
  @Column({nullable: true})
  url: string;

  /** A description of this video. Nullable. */
  @Column({nullable: true})
  description: string;

  /** All tags associated with this video. */
  @ManyToMany(type => Tag, tags => tags.videos)
  @JoinTable()
  tags: Tag[];

  /** All Programs containing this video. */
  @ManyToMany(type => Program, program => program.videos)
  programs: Program[];

  /** All subject Responses to this video. */
  @OneToMany(type => Response, responses => responses.video)
  responses: Response[];

  public static async createEmptyVideo(): Promise<string> {
    let videoRepo = getRepository(Video);
    let video = new Video();
    await videoRepo.save(video);
    return video.id;
  }

  /** Saves a new Video to the database. */
  public static async uploadAsync(videoOptions: VideoUploadOptions): Promise<Video> {
    let videoRepo = await getRepository(Video);
    let tags: Tag[] = [];
    if (videoOptions.tags) {
      await Promise.all(videoOptions.tags.map(async (tagName) => {
        tags.push(await Tag.findByNameAsync(tagName));
        return;
      }));
    }
    let newVideo = new Video();
      newVideo.id = videoOptions.id
      newVideo.url = videoOptions.url;
      newVideo.description = videoOptions.description;
      newVideo.tags = tags;
    return videoRepo.save(newVideo);
  }

  public static async deleteVideoId(videoId) {
    let videoRepo = await getRepository(Video);
    let videoToDelete = await videoRepo.findOneById(videoId);
    await videoRepo.remove(videoToDelete);
    let check = await videoRepo.findOneById(videoId);
    if(check) {
      console.log(videoId);
      return false;
    } else {
      console.log(videoId);
      return true;
    }
  }
}

/** All options required to create a new Video. */
export interface VideoUploadOptions {
  /** The id where this video will be stored */
  id: string;
  /** The URL where this video is stored. */
  url: string;
  /** A description of this video. */
  description: string;
  /** All tags associated with this video. Optional. */
  tags?: TagName[];
}
